### ISSUE TITLE
How to slugify the ID's with markdown-it-anchor

### ISSUE THREAD

**Issue by mikem33** [niemingzhao/hexo-renderer-markdown#2]
Hi! Is there a way to 'slugify' the ID's? In the documentation of markdown-it-anchor explains that it is possible but in your example that option it's missing. If a try to set it in the _config.yml I get an error. Thanks in advance!

**Comment by niemingzhao** [comment]
> Hi! Is there a way to 'slugify' the ID's? In the documentation of markdown-it-anchor explains that it is possible but in your example that option it's missing. If a try to set it in the _config.yml I get an error. Thanks in advance!

YAML format does not support parsing functions of JS, so the plugin's options such as 'slugify' of markdown-it-anchor could not be specified in _config.yml gracefully. I still implemented an awkward way to specify 'function' in _config.yml with 'eval'. You can attempt to use the new version that I published just now.
