### ISSUE TITLE
怎么关掉katex

### ISSUE THREAD

**Issue by justin-xjp** [niemingzhao/hexo-renderer-markdown#5]
误打误撞安上了这个，居然能完整的实现typora的语法，基本完全通用，我没搞懂markdown-it，没弄出应有的效果。可是这里用的katex没有默认的marked公式好看，我想用回marked的样式，怎么关掉katex？

**Comment by niemingzhao** [comment]
在_config.yml——markdown——plugins——markdown-it-katex下面设置disabled:true。请参考本项目readme文件。如果只是想更改katex样式，可以在csslink设置想用的样式文件的CDN链接。如果想换用其他公式显示插件比如mathjax，可以disable markdown-it-katex后按照readme上的提示Add markdown-it-mathjax类型的插件。
